# Generated by Django 4.2 on 2023-04-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roll',
        ),
    ]
