# Generated by Django 4.2 on 2023-04-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_delete_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facoltà',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificativo', models.CharField(max_length=8)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
    ]
