# Generated by Django 4.2 on 2023-04-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_facoltà'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='prezzo',
        ),
        migrations.AddField(
            model_name='exam',
            name='anno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
