# Generated by Django 4.2 on 2023-04-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_exam_prezzo_exam_anno'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='semestre',
            field=models.IntegerField(choices=[(1, '1° Semestre'), (2, '2° Semestre')], default=1),
            preserve_default=False,
        ),
    ]
