# Generated by Django 4.2 on 2023-04-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='anno',
            field=models.IntegerField(choices=[(1, 'Primo Anno'), (2, 'Secondo Anno'), (3, 'Terzo Anno')]),
        ),
    ]
