# Generated by Django 4.2 on 2023-04-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_exam_anno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.RemoveField(
            model_name='facoltà',
            name='identificativo',
        ),
        migrations.AddField(
            model_name='facoltà',
            name='anno',
            field=models.IntegerField(choices=[(1, 'Primo Anno'), (2, 'Secondo Anno'), (3, 'Terzo Anno')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facoltà',
            name='semestre',
            field=models.IntegerField(choices=[(1, '1° Semestre'), (2, '2° Semestre')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facoltà',
            name='nome',
            field=models.IntegerField(),
        ),
    ]
