# Generated by Django 4.2 on 2023-04-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_delete_exam_remove_facoltà_identificativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facoltà',
            name='nome',
            field=models.IntegerField(choices=[(1, 'Ingegneria Informatica'), (2, 'Ingegneria Meccanica'), (3, 'Ingegneria Gestionale'), (4, 'Ingegneria Del Veicolo'), (5, 'Ingegneria Elettronica'), (6, 'Ingegneria Robotica')]),
        ),
    ]
