# Generated by Django 4.2 on 2023-04-04 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_facoltà_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddConstraint(
            model_name='facoltà',
            constraint=models.UniqueConstraint(fields=('nome', 'anno', 'semestre'), name='unique_migration_nome_anno_semestre'),
        ),
        migrations.AddField(
            model_name='exam',
            name='Facoltà',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.facoltà'),
        ),
    ]
