# Generated by Django 4.2 on 2023-04-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_rename_facoltà_exam_facoltà'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='crediti',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('nome', 'anno', 'semestre'), name='unique_migration_exam'),
        ),
    ]
