# Generated by Django 4.2 on 2023-04-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_exam_crediti_exam_id_alter_exam_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facoltà',
            name='anno',
            field=models.IntegerField(choices=[(1, 'Primo Anno'), (2, 'Secondo Anno'), (3, 'Terzo Anno')], default=3),
            preserve_default=False,
        ),
    ]
