# Generated by Django 4.2 on 2023-04-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_facoltà_anno'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='facoltà',
            name='unique_migration_nome',
        ),
        migrations.AddConstraint(
            model_name='facoltà',
            constraint=models.UniqueConstraint(fields=('nome', 'anno'), name='unique_migration_nome_anno'),
        ),
    ]
