# Generated by Django 4.2 on 2023-04-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_remove_facoltà_unique_migration_nome_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exam',
            name='unique_migration_exam',
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('nome', 'anno', 'semestre', 'facoltà'), name='unique_migration_exam'),
        ),
    ]
