# Generated by Django 4.2 on 2023-04-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_dateexam'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dateexam',
            constraint=models.UniqueConstraint(fields=('data', 'exam'), name='unique_migration_DateExam'),
        ),
    ]
