# Generated by Django 4.2 on 2023-05-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_dateexam_unique_migration_dateexam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.IntegerField(choices=[(1, 'FA-2F'), (2, 'Fa-2g'), (3, 'FA-2E')])),
                ('data', models.DateTimeField()),
                ('span_disponibilità', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='aula',
            constraint=models.UniqueConstraint(fields=('data', 'nome', 'span_disponibilità'), name='unique_migration_Aula'),
        ),
    ]
